---
title: "Week-02-Notes"
author: "Andrew Nalundasan"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Week 2 Overview Video

+ Prof Andy is a skier! Went to Cairngorm with wife and 2 girls for a ski sesh
+ Communications - email and slack (@Prof.Andy)
+ Class materials - released on Friday's
+ Will review problem sets in overview videos
+ Need to learn how to do this the best way possible
+ Finish watching lecture videos prior to assignment videos
+ Everyone will have their own 5 DB's
+ Ensure can access my own DB
+ Files > scripts for creating DB's

    + DB Schema example
    + Example Data
    + ignore modification scripts - don't need for this course
    
+ Next week:

    + go over queries
    + talk about DTC
    + feedback
    

# 02-01: SQL & SQL Server

## Structured Query Language

+ Breaks - actually go do the work that's assigned. Not everything is graded, but it's all extremely important
+ SQL - standard language based on the relational model, for querying and managing data in a Relational DBMS

    + SQL is a non-procedural language
    + SQL cannot write complete applications
    + No inherent user-interface
    + SQL is used in conjunction with Procedural languages (R, Python, Java, C#)
    + SQL is declarative (not imperative)
        + we specify what we want
        + DBMS decides how to get it
    + e.g.: 
        + "Get all the products that have sold more than 500 units in the last 2 years, but only for North America"
    + SQL optimizes how to execute queries
        

## SQL History and SQL Server

+ Relational Model began ~ 1970 in a computer
+ SEQUEL 1974 was beginning of what we do today
+ Relational Software 1979 renamed to Oracle
+ ANSI standardized in 1982
+ dBase IV was first version of being a true relational DB

+ SQL Products

    + Mainframe
        + Oracle
        + IBM DB2
        + Ingres
    + Client/Server - Web Server
        + Microsoft SQL Server
        + Oracle
        + MySQL
        + PostgreSQL
    + Desktop
        + Access
        + Most server products
        
+ Microsoft SQL Server

    + Instance-based
        + multiple instances can be installed multiple times on a single server
        + 1 instance, multiple DB's
        + separate instances, separate versions if desired (support older legacy applications)
    + multiple installs on a single server
    + performance control at an instance level
    + security separation at an instance level
    + supports multiple versions for legacy databases
    + must reference a connection string


# 02-02: SQL Database Setup

## Create Databases and Load Data

+ create DB's
+ snodgrass has downloaded all the scripts and created the DB's for us
+ 2 versions of DB's

    + "Example" - early on in the book
    + "Modify" - more advanced
    
+ Snodgrass already created all DB's for us and inserted all data into the tables

## Database Diagram Assignment

+ Need some kind of a schema diagram
+ Create the DB diagram for each DB and grab screen shots
+ Do not submit schema files on Canvas
+ gain familiarity with the DB and its structure


# 02-03: Chp 4 SELECT and ORDER BY

## Assignment

Do all "Problems for You" at end of Chapter 

+ Submit results in a Word document
+ Take questions they have and translate into SQL statement

## SELECT

+ SELECT is the heart of most queries
+ Main thing analysts want to do is to SELECT data
+ Art of an analyst - translate the question into a query

+ SELECT Statement

    + we SELECT columns
    + specify FROM which table the columns need to come from 
    + specify WHERE the condition should look
    + GROUP BY will take the statement and aggregate it to sort it in a specified manner
    + HAVING is a search condition in scenarios that use GROUP BY
    
+ Simple SELECT statement

    1. "Show me a list of all employees"
    + where do I get the data <- Employees
        + SELECT * FROM Employees;
        + SELECT EmpLastName FROM Employees
        + SELECT EmpLastName, EmpFirstName FROM Employees;
    2. "Where do our customers live?" <- Customers
        + always good to get clarification for what's being asked - be CURIOUS!
        + SELECT * FROM Customers;
        + SELECT CustCity FROM Customers;
        + DISTINCT will return alphabetized list
        + SELECT DISTINCT CustCity, CustSTate FROM Customers;
    + Practice SELECT!

## ORDER BY

+ ORDER BY - sorts the query results
+ Can use 1 or more columns
+ Result set uses the system's collating sequence (depending on DB and way its configured)

    + Uppercase before lowercase
    + Numbers before letters
    + Year, month, date
    
+ Start off with standard SELECT statement
+ Near end of SELECT statement is where ORDER BY clause is inserted 

    1. List vendors by zipcode
        + SELECT VendName, VendZipCode FROM Vendors
          ORDER BY VendZipCode DESC
        + ASC is default
    2. List employees by name
        + SELECT EmpLastName, EmpFirstName, EmpPhoneNumber, EmployeeID FROM
          Employees ORDER BY EmpLastName DESC, EmpFirstName ASC

+ Can select columns not part of SELECT statement

# 02-04: Chp 5 Expressions and Functions

+ All about moving beyond simple columns
+ want to do more than just show the data - need to do analyses on them!
+ this is done similar to excel
+ how to create columns that do more than just show simple data via Expressions
+ This class is about querying data, not about building DB's

    + As an analyst, we must recognize the data types or know how to change them to do what we need to do
    
## Assignments

Do all 12 problems at end of chapter for assignment
+ Submit results in a word document

## Expressions and CAST

+ Expression <- an operation involving number, text, date, or time

+ Data Types

    1. Character
        + Exact or variable
    2. Binary, BLOB
    3. Numeric
        + Integer, Float, Real, Currency, Digits
    4. Boolean
    5. DateTime
        + Date, DateTime, Time, Interval

+ CAST

    + Data types are not always compatible
    + CAST allows conversion from one data type to another
        + Converting an integer to decimal for averaging
        + Converting datetime to date only for comparison
        + Converting to the same character format for combining text
        + Converting date to text to include in a string

+ CAST Example

    + money datatype 
        + SELECT quotedprice FROM Order_Details
        + SELECT CAST(quotedprice AS numeric(12, 3))  # 12 digits, with 3 decimal points of precision
          FROM Order_Details
        

## Expression Naming

+ Literals - things used in calculations and filtering

+ Expressions

    + Calculated Columns should be named - ALWAYS NAME your calculated columns!
        + "AS" is your friend
        + Use it frequently
    + Calculated Columns
        + Literals
        + Functions
            + String
            + Mathematical
            + Date and time
            
+ Naming Columns

    + Name columns on expressions - always a good idea to NOT have "unnamed columns"
    + Rename columns of existing fields
        + SELECT EmpLastName AS LastNAME FROM Employees
        + SELECT VendorName AS Vendor FROM Vendors;
        + SELECT vrQty AS BidQuantity, axQty AS AgreedQuantity, dlQty AS DeliveredQuantity FROM SalesOrders;  # dealing with different "quantity" fields
        
+ Literals

    + String literals
    + Numeric literals
    + Datetime literals
        + SELECT 'Name:' AS NameHeader, EmpLastName FROM Employees;
        + SELECT BowlerID, RawScore FROM Bowlers_Scores WHERE RawScore > 225;


## CONCAT and Formulas

+ Will frequently use CONCAT
    
    + For combining and working with Strings
    1. Show me a list of all employees
        + SELECT EmpLastName, EmpFirstName, FROM Employees
        + SELECT CONCAT(EmpFirstName, '', EmpLastName) AS EmployeeName FROM Employees;
        
+ Formulas

    + Regular mathematical calculations
        1. List product prices with a 10% increase
            + SELECT retailprice, (retailprice * 1.10) AS newprice FROM Products;
        2. What is our profit margin on last month's sales?
        3. What happens to gross margin by product if sales are 10% lower for three months?

## Functions and NULL

+ Functions <- enable you to use pre-built calculations and tools for manipulating data
+ Functions

    + Aggregate
    + Analytica
    + Conversion
    + Date & Time
        + Date functions are fantastic for manipulation!
    + Mathematical
    + Logical
    + String
    + https://docs.microsoft.com/en-us/sql/t-sql/functions/functions?view=sql-server-ver15
    
+ NULL

    + We handle null with a function
    + Null <- absence of a value
        + NOT a 0 value
        + NOT a blank space
        + NOT a 0-length string
    + **NULL breaks formulas and expressions**
    + ISNULL()
        + SELECT ISNULL(RawScore, 0) AS RawScoreClean
          FROM Bowlers_Scores; 


# 02-05: Chp 6 Filtering

## Assignment

+ Chapter 6 problem set
+ do all of them
+ 

## Filtering Data

+ How do you filter the data down so you get just the results you need

+ WHERE statement

    + this is the artform piece of a SELECT query
    + comparative set of conditions that returns TRUE/FALSE/Unknown
    + Search conditions:
        + =, <>, !=, >, >=, <, <=
        + LIKE, BETWEEN, IN, IS NULL, NOT LIKE NOT BETWEEN, NOT IN, IS NOT NULL
        + AND, OR
    + Just like building a formula - need parenthesis
    + https://docs.microsoft.com/en-us/sql-t-sql/queries/where-transact-sql?view=sql-server-ver15
    

## Comparisons

+ Standard arithmetic comparisons

    + SELECT CustLastName FROM Customers
      WHERE CustLastName = 'Smith';
    + SELECT CustLastName FROM Customers
      WHERE CustState = 'WA'; 
        + must know data well enough to know that the states are abbreviated
        + must be mindful of collating sequence in your management tool
        
+ Compound filtering

    + SELECT CustLastName FROM Customers
      WHERE Cust State = 'WA'
      AND CustCity <> 'Bellevue'; 
    + SELECT CustLastName FROM Customers
      WHERE Cust State = 'WA'
      AND CustCity <> 'Bellevue'
      AND CustCity <> 'Seattle'
    + SELECT CustLastName FROM Customers
      WHERE
      (CustState = 'WA' AND CustCity <> 'Seattle') OR
      (CustState = 'OR' AND CustCity <> 'Portland') OR
      (CustState = 'ID' AND CustCity <> 'Boise' AND CustCity <> 'Twin Falls');
    + Same results, different approaches: 
    1. SELECT CustLastName FROM Customers
       WHERE
       (CustState = 'WA' AND CustCity <> 'Seattle') OR
       (CustState = 'OR' AND CustCity <> 'Portland') OR
       (CustState = 'ID' AND CustCity <> 'Boise' AND CustCity <> 'Twin Falls');
    2. SELECT CustLastName FROM Customers
       WHERE
       (CustState = 'WA' OR CustState = 'OR' OR CustState = 'ID') AND 
       (CustCity <> 'Seattle' AND AND CustCity <> 'Portland' AND CustCity <> 'Boise' AND CustCity <> 'Twin Falls')
       
+ Complex
"Customers from Seattle who spent more than $25,000 in the last two years"

    + SELECT CustLastName FROM CustomerSales
      WHERE
      (CustState = 'WA' AND CustCity = 'Seattle') AND
      (CustQty * ProductPrice > 25000) AND
      (CustOrderDate >= '2018-01-01)
      
+ Be Careful

    + Potential for returning nothing
    + SELECT CUstLastName FROM Customers
      WHERE
      (CustState = 'WA' AND CustCIty <> 'SEattle') AND
      (CustState = 'OR' AND CustCity <> 'Portland'); 
    + Because using AND for comparison which returns nothing

## LIKE

+ Condition statement to insert into WHERE clause - Pattern matching

    + SELECT EmployeeKey, LastName FROM Employees
      WHERE LastName LIKE 'Smith%';
    + % - wildcard that looks for anything that start with 'Smith', and I don't care what happens after that
    + SELECT ProductName, ProductDescription FROM Products
      WHERE ProductName LIKE '%blue%' OR
      ProductDescription LIKE '%blue%';
        + case sensitive
    + SELECT ProductName, ProductDescription FROM Products
      WHERE LOWER (ProductName) LIKE '%blue%' OR
      LOWER(ProductDescription) LIKE '%blue%';
        + manipulate to lowercase first, prior to wildcard search since case sensitive
        
+ Pattern Matching

    + SELECT * FROM Sales
      WHERE LOWER(SalesNotes) LIKE '%discount%'; 
    + SELECT * FROM SupportCalls
      WHERE LOWER(CallText) LIKE '%refund%';
    + SELECT * FROM EquipmentLog
      WHERE LOWER(LogEntry) LIKE '%error%';
      

## BETWEEN

+ determines data that fits within a range

    + SELECT LastName FROM Employees
      WHERE DateHired BETWEEN '2019-01-01' AND
      '2019-12-31';
        + always format dates as YYYY-MM-DD
    + Employees with 14-28 days of PTO (2 acceptable approaches)
        1. SELECT LastName FROM Employees
           WHERE VacationDays BETWEEN 14 AND 28;
        2. SELECT LastName FROM Employees
           WHERE VacationDays >= 14 AND
           VacationDays <= 28
    + Sales staff who met mid-range targets last month
        + SELECT LastName FROM SalesTeam
          WHERE SalesMetric BETWEEN 4 AND 7; 
          ...and calc on how to get to 'last month'
          
+ IN (membership)

Customers in and around Seattle

    + SELECT CustName FROM Customers
      WHERE CustCity IN('Seattle', 'Kirkland', 'Redmond', 'Bothell'); 
    + SELECT CUstName FROM Customers
      WHERE CustCity = 'Seattle' OR CustCity = 'Kirkland', OR
      CustCity = 'Redmond' OR CustCity = 'Bothell'; 

Vendors on the west coast that placed large order (> 50k last year)

    + SELECT * FROM VendorOrders
      WHERE VendState IN ('WA', 'CA', 'OR', 'NV', 'NM') AND
      VendSalesAmount > 50000 AND
      VendSalesOrderDate BETWEEN '2019-01-01' AND '2019-12-31';


## IS NULL, NOT

+ IS NULL

    + Equipment not submitting full log data
    + Meant to be used in a WHERE clause
    + SELECT EquipID FROM EqpLog
      WHERE TempVal IS NULL OR
      PressVal IS NULL OR FlowVal IS NULL; 
      
+ Employees without evaluations

    + SELECT EmpLastName FROM Employee
      WHERE EvalDate IS NULL;

+ NOT

    + SELECT LastName FROM Employees
      WHERE (DateHired BETWEEN '2019-01-01' AND
      '2019-12-31') AND NOT EmpDept = 'Sales'; 
    + SELECT LastName FROM Employees
      WHERE (DateHired BEWEEN '2019-01-01' AND
      '2019-12-31') AND
      EmpDept NOT IN ('Sales', 'Service', 'Support');
      
+ Functions

    + SELECT * FROM Sales
      WHERE LOWER(SalesNotes) LIKE '%discount%'; 
    + SELECT * FROM Products
      WHERE SUBSTRING(ProdCategory,3,2) = 'UC'; 
          + Product Category where start position 3 and length 2 
    + SELECT * FROM Employees
      WHERE YEAR(EmpBirthDate) < 1980;
          + this will extract the year from the column
    
    



